name: build_production_image
on:
  release:
    types:
      - published
      - edited
jobs:
  get_tags_atlas:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.prep.outputs.tags }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=ghcr.io/alercebroker/atlas_stamp_classifier_step
          VERSION=latest
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest"
          fi
          echo ::set-output name=tags::${TAGS}
  push_image_atlas:
    needs: get_tags_atlas
    uses: ./.github/workflows/build-atlas.yaml
    with:
      tags: ${{ needs.get_tags_atlas.outputs.tags }}
    secrets:
      PUBLISH_IMAGE_TOKEN: ${{ secrets.PUBLISH_IMAGE_TOKEN }}
      INSTALL_PRIVATE_REPO: ${{ secrets.ADMIN_TOKEN }}
  get_tags_ztf:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.prep.outputs.tags }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=ghcr.io/alercebroker/ztf_stamp_classifier_step
          VERSION=latest
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest"
          fi
          echo ::set-output name=tags::${TAGS}
  push_image_ztf:
    needs: get_tags_ztf
    uses: ./.github/workflows/build-ztf.yaml
    with:
      tags: ${{ needs.get_tags_ztf.outputs.tags }}
    secrets:
      PUBLISH_IMAGE_TOKEN: ${{ secrets.PUBLISH_IMAGE_TOKEN }}
      INSTALL_PRIVATE_REPO: ${{ secrets.ADMIN_TOKEN }}